name: QA GATE

on:
  pull_request:
    branches:
      - main

jobs:
  prepare:
    name: Get changed charts(s)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50  # To retrieve all commits
      - name: Get changed helm chart(s)
        id: changes-as-json
        uses: dawidmalina/actions-hub/wrapped-changed-directories@main
        with:
          dir_names_max_depth: "5"
          files_ignore: |
            .github

    outputs:
      all_changed_files: ${{ steps.changes-as-json.outputs.all_changed_files }}
      any_changed: ${{ steps.changes-as-json.outputs.any_changed }}

  validate:
    name: Validate changed helm chart(s)
    if: needs.prepare.outputs.any_changed == 'true'
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        dir: ${{ fromJson(needs.prepare.outputs.all_changed_files) }}
    steps:
      - uses: actions/checkout@v3
      - name: Run script file
        run: |
           echo ${{ matrix.dir }}
