name: Terraform Drift

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'
#     - cron: '0 0 * * 6' # Runs every Saturday at midnight

jobs:
  call-terraform-workflow:
    name: "workflow"
    uses: dawidmalina/actions-hub/.github/workflows/terraform-drift-gcp.yml@main
    with:
      product: 'astrato'
    secrets: inherit
