name: Terraform

on:
  pull_request:
    # paths: # setup paths if necessary
    branches:
      - main
    types:
      - opened # default
      - synchronize # default
      - reopened # default
      - closed # needed to handle action after merge

jobs:
  call-terraform-workflow:
    name: "workflow"
    uses: dawidmalina/actions-hub/.github/workflows/simple-test.yml@main
    # with:
    #   product: 'malina'
    secrets: inherit
