name: Terraform

on:
  pull_request:
    # paths: # setup paths if necessary
    branches:
      - main
    types:
      - opened # default
      - synchronize # default
      - reopened # default
      - closed # needed to handle action after merge

jobs:
  call-terraform-workflow:
    name: "workflow"
    uses: dawidmalina/actions-hub/.github/workflows/terraform-gcp.yml@main
    with:
      working_dir: '.'
      project_id: '123456'
    secrets:
      GOOGLE_CREDENTIALS: '222'
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
