name: Test release

on:
  push:
    tags:
      - 'v*'
    branches-ignore:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: verify actor
        run: |
          echo ${{ github.actor }}
          echo ${{ github.event }}
