name: Test release

on:
  push:
    tags:
      - '**/v*'
    branches-ignore:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"