on:
  workflow_call:
    inputs:
      env_vars:
        description: "Define environment variables to pass to workflow"
        type: string
        required: false
        default: ''

jobs:
  parse-envs:
    runs-on: windows-latest
    env:
      env_vars: ${{ inputs.env_vars }}
    steps:
      - name: Decode envs as environment variables
        if: inputs.env_vars != ''
        run: |
          # debug
          echo $env_vars

          $env_vars.Split(" ") | ForEach-Object {
            $name, $value = $_ -split "=", 2
            Add-Content -Path $env:GITHUB_ENV -Value "$name=$value"
          }

      - name: Validate envs
        run: |
          echo $VAR1 ${{ env.VAR1 }}
          echo $VAR2 ${{ env.VAR2 }}
