name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      project_path:
        description: "Define project path (ex gcp/prod/global)"
        required: true
        type: string
      approvers:
        description: "Define workflow approvers"
        type: string
        default: |
          [
            "k-madejski",
          ]
        


jobs:
  promote:
    runs-on: ubuntu-latest
    container:
      image: node:18.19
    steps:
      - name: verify actor
        run: |
          echo ${{ github.actor }}
          echo ${{ github.triggering_actor }}

          echo ${{ inputs.approvers }}

          echo ${{ fromJSON(inputs.approvers) }}

          node .github/workflows/test.js "${{ fromJSON(inputs.approvers) }}" ${{ github.triggering_actor }}
# jobs:
#   call-terraform-workflow:
#     name: "workflow"
#     uses: dawidmalina/actions-hub/.github/workflows/terraform-apply-gcp.yml@main
#     with:
#       product: 'astrato'
#       project_path: ${{ inputs.project_path }}
#     secrets: inherit
