on:
  workflow_call:
    inputs:
      env_vars:
        description: "Define environment variables to pass to workflow"
        type: string
        required: true

jobs:
  parse-envs:
    runs-on: ubuntu-latest
    env:
      env_vars: ${{ inputs.env_vars }}
    steps:
      - name: Decode envs as environment variables
        run: |
          # debug
          echo $env_vars

          for e in $env_vars; do
            i=$( echo $e | sed 's/=.*//g')=$(echo ${e#*=} )
            printf '%s\n' "$i" >> $GITHUB_ENV
          done

      - name: Validate envs
        run: |
          echo $VAR1 ${{ env.VAR1 }}
          echo $VAR2 ${{ env.VAR2 }}
