name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      project_path:
        description: "Define project path (ex gcp/prod/global)"
        required: true
        type: string

jobs:
  call-terraform-workflow:
    name: "workflow"
    uses: dawidmalina/actions-hub/.github/workflows/terraform-apply-gcp.yml@main
    with:
      product: 'astrato'
      project_path: ${{ inputs.project_path }}
    secrets: inherit
